name: hunger_free_kerala
description: "A new Flutter project."
# Prevent the package from being published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Define the version and build number for your application.
# Version format: MAJOR.MINOR.PATCH+BUILD
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # Specify the Dart SDK version range

# Dependencies specify other packages needed for the project.
dependencies:
  flutter:
    sdk: flutter # Include Flutter SDK

  # Add the Cupertino Icons font for iOS style icons
  cupertino_icons: ^1.0.6
  
  # Include Hive for local storage
  hive_flutter: ^1.1.0 # Flutter integration for Hive
  hive_storage: ^0.0.3  # Storage for Hive
  hive_generator: ^2.0.1 # Code generation for Hive
  hive: ^2.2.3 # Core Hive package
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter # Flutter testing framework

  # Recommended lints for good coding practices
  flutter_lints: ^3.0.0

# Flutter specific configuration
flutter:
  uses-material-design: true # Enable Material Design

  # Assets section to include images and other resources
  assets:
    - assets/onboarding.jpeg
    - assets/home1.jpg
    - assets/homeright1.jpeg
    - assets/homeright2.jpeg
    - assets/homeright3.jpeg
    # Uncomment and add more assets as needed
    # - images/a_dot_ham.jpeg

  # To add custom fonts, uncomment and modify the following section
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
